help:	## print Help Massage
	@fgrep -h "#" $(MAKEFILE_LIST) | fgrep-V fgrep | sed -e 's/\\$$//' | sed -e 's##//'

Frontend:	##  Install Frontend Component
	@sh components/frontend.sh

Mongodb:	##	Install Mongodb Component
	@sh components/Mongodb.sh


Catalogue:	## Install Catalogue Component
	@sh Components/Catalogue.sh

Redis:		##	Install Redis Components
	@sh compnenrs/Redis.sh

User:		##Install User Componenets
	@sh Components/User.sh

Crat:		##Install Cart Componenets
	@sh Components/Cart.sh

Mysql:		## Install Mysql Components
	@sh Componenets/Mysql.sh


Shipping:	## Install Shipping Componenets
	@sh Componenets/Shipping.sh


Payment:	## Install Paymemt Componenets
	@sh Componenets/payment.sh


Rabitmq:	## Install Rabitmq Components
	@sh components/Rabitmq

