help:	## print Help Massage
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's##//'

Frontend:	##	Install Frontend Component
	@sh Components/frontend.sh

Mongodb:	##	Install Mongodb Component
	@sh Components/Mongodb.sh


Catalogue:	##	Install Catalogue Component
	@sh Components/Catalogue.sh

Redis:		##	 Install Redis Components
	@sh Components/Redis.sh

User:		##	Install User Componenets
	@sh Components/User.sh

Crat:		##	Install Cart Componenets
	@sh Components/Cart.sh

Mysql:		##	Install Mysql Components
	@sh Components/Mysql.sh


Shipping:	##	Install Shipping Componenets
	@sh Components/Shipping.sh


Payment:	##	Install Paymemt Componenets
	@sh Components/payment.sh


Rabitmq:	##	Install Rabitmq Components
	@sh Components/Rabitmq

